from __future__ import annotations

import contextlib
import os
import time
from pathlib import Path
from uuid import uuid4
import base64
from typing import cast
from pgvector.sqlalchemy import Vector
from openai import AsyncOpenAI
import structlog

from app.models.models import Toy
from app.lib.database import AsyncSessionLocal

from fastapi import HTTPException, UploadFile

logger = structlog.get_logger(__name__)

MAX_TOY_IMAGE_BYTES = 10 * 1024 * 1024
TOY_IMAGE_PUBLIC_PATH_ENV = "TOY_IMAGE_PUBLIC_PATH"
TOY_IMAGE_STORAGE_DIR_ENV = "TOY_IMAGE_STORAGE_DIR"
LOCAL_EMBEDDING_BASE_URL_ENV = "LOCAL_EMBEDDING_BASE_URL"

_ALLOWED_IMAGE_MIME_TYPES = {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/gif": ".gif",
    "image/webp": ".webp",
}

_ALLOWED_IMAGE_SUFFIXES = {
    ".jpg": ".jpg",
    ".jpeg": ".jpg",
    ".png": ".png",
    ".gif": ".gif",
    ".webp": ".webp",
}


def get_toy_image_storage_dir() -> Path:
    return Path(os.environ.get(TOY_IMAGE_STORAGE_DIR_ENV, "/data/images"))


def get_toy_image_public_path() -> str:
    return os.environ.get(TOY_IMAGE_PUBLIC_PATH_ENV, "/images")


def build_toy_image_public_path(filename: str) -> str:
    prefix = get_toy_image_public_path().rstrip("/")
    return f"{prefix}/{filename}"


def resolve_toy_image_storage_path(public_path: str) -> Path:
    return get_toy_image_storage_dir() / Path(public_path).name


def delete_toy_image(public_path: str | None) -> None:
    if not public_path:
        return
    prefix = get_toy_image_public_path().rstrip("/")
    if not public_path.startswith(f"{prefix}/"):
        return
    with contextlib.suppress(FileNotFoundError):
        resolve_toy_image_storage_path(public_path).unlink()


def _resolve_image_suffix(upload: UploadFile) -> str:
    content_type = (upload.content_type or "").lower()
    if content_type in _ALLOWED_IMAGE_MIME_TYPES:
        return _ALLOWED_IMAGE_MIME_TYPES[content_type]

    suffix = Path(upload.filename or "").suffix.lower()
    if suffix in _ALLOWED_IMAGE_SUFFIXES:
        return _ALLOWED_IMAGE_SUFFIXES[suffix]

    raise HTTPException(
        status_code=400,
        detail="Only JPEG, PNG, GIF, and WEBP images are supported.",
    )


async def save_toy_image(upload: UploadFile) -> str:
    suffix = _resolve_image_suffix(upload)

    storage_dir = get_toy_image_storage_dir()
    storage_dir.mkdir(parents=True, exist_ok=True)

    filename = f"{uuid4().hex}{suffix}"
    with open(storage_dir / filename, "wb") as buffer:
        buffer.write(await upload.read())
    return build_toy_image_public_path(filename)


OPENAI_MODEL = "gpt-4o"
OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"

_client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))
_local_client = AsyncOpenAI(
    base_url=os.environ.get(
        LOCAL_EMBEDDING_BASE_URL_ENV, "http://192.168.1.113:8080/v1"
    ),
    api_key="None Needed for local",
)


async def describe_image(image_path: str) -> str:
    """
    Passes an image to OpenAI and returns the description generated by the chosen model
    """
    storage_path = resolve_toy_image_storage_path(image_path)
    with open(storage_path, "rb") as image_file:
        base64_image = base64.b64encode(image_file.read()).decode("utf-8")

    response = await _client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            "Describe this toy in detail. This description will be used to identify the toy in searches later. "
                            "If you know anything about the brand, manufacturer or name of the character the toy is meant to "
                            "portray, please also include that information."
                        ),
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"},
                    },
                ],
            }
        ],
    )
    return response.choices[0].message.content or ""


async def embed_description(description: str) -> list[float]:
    """Generates a vector embedding for a given text string using the local embedding model."""
    start = time.perf_counter()
    response = await _local_client.embeddings.create(
        # llama uses whatever is loaded, so we may as well use the openAI value here.
        model=OPENAI_EMBEDDING_MODEL,
        input=description,
    )
    elapsed = time.perf_counter() - start
    logger.info(
        "local_embedding_request_completed",
        elapsed_seconds=round(elapsed, 3),
    )
    return response.data[0].embedding


async def toy_embedding(
    toy_id: int,
) -> None:
    """
    Generates a description for the toy using OpenAI models
    then vectorizes that description.

    Persists both to the toy model once complete.
    """
    async with AsyncSessionLocal() as db:
        toy = await db.get(Toy, toy_id)
        if toy is None:
            raise ValueError(f"Toy id {toy_id} not found in DB")
        if toy.image_path is None:
            raise ValueError(f"Toy id {toy_id} does not have an image")

        description = await describe_image(toy.image_path)
        vector = await embed_description(
            ". ".join([toy.title, (toy.description or ""), description])
        )
        toy.embedding, toy.ai_description = cast(Vector, vector), description

        await db.commit()
